### ISSUE TITLE
run for win, mac and linux

### ISSUE THREAD

**Issue by dragonyanglong** [conda-forge/diffpy.pdfgui-feedstock#20]
### Comment:

@conda-forge-admin
@conda-forge/help-python 

when this package was first set up at conda-forge (https://github.com/conda-forge/staged-recipes/pull/21620), it shows versions for win, os, linux.

But now when I try to update the recipe metadata and update package (from v1.4.0 -> v1.4.2), only linux is updated? (https://anaconda.org/conda-forge/diffpy.pdfgui) How to update globally for win, os, linux?

Thanks!

**Comment by beenje** [comment]
I see new windows and macOS packages have been published now. So looks like your issue was solved.
If the recipe is `noarch`, only Linux is built. It's not the case here. I'd have suggested to re-render the recipe.

**Comment by beenje** [comment]
Is the noarch version broken? If it is, you could open a PR in this repo https://github.com/conda-forge/admin-requests

If not, I guess it can stay.

**Comment by dragonyanglong** [comment]
Thanks!
